export const ANIMATION_CONFIG = {
    PICKUP_RADIUS: 20,
    BASE_SPEED_PX_PER_SEC: 50,
    MAX_ADDITIONAL_SPEED_PX_PER_SEC: 350,
    DEFAULT_SPEED_PERCENT: 50,
    INSTANT_ACTION_DURATION: 1.0,
    ZERO_LENGTH_DURATION: 1.0,
    // Visuals
    BALL_RADIUS: 6,
    BALL_COLOR_DEFAULT: '#FFA500',
    BALL_COLOR_MOVING: '#FFA500',
    BALL_STROKE_COLOR: '#fff'
};
